# site title
title: blog

# user name or organization name
user: jordzhang

# issue repository
repository: blog

# multi-author
authors: jordzhang

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: bd1c3a52aaeafe946f7b3f116d081e05949c248a

# posts per page
perpage: 10


# advance config

# organization repository (?)
organization: false

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'UPDATED_AT'
